create sequence hibernate_sequence start with 1 increment by 1;
create table inquiry (id bigint not null, amount_in_euros double, customer_name varchar(255), score integer, status varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table inquiry (id bigint not null, amount_in_euros double, customer_name varchar(255), score integer, status varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table inquiry (id bigint not null, amount_in_euros double, customer_name varchar(255), score integer, status varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table inquiry (id bigint not null, amount_in_euros double, customer_name varchar(255), score integer, status varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table inquiry (id bigint not null, amount_in_euros double, customer_name varchar(255), score integer, status varchar(255), primary key (id));
