package com.example.workflow.creditrequest.workflow;

public enum CreditRequestStatusEnum {
    APPROVAL_PROCESS_STARTED,
    VALID_REQUEST,
    NON_VALID_REQUEST,
    SOLVENCY_CHECK_FAILED,
    SOLVENCY_CHECK_SUCCESSFUL,
    MONEY_TRANSFERRED,
    REQUEST_ARCHIVED,
    REQUEST_APPROVED,
    NON_VALID_REQUEST_REJECTED,
    REQUEST_REJECTED_DUE_TO_SOLVENCY;
}
